version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
  ignore:
  - dependency-name: "io.rest-assured:rest-assured"
    update-types: ["version-update:semver-major"]
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  assignees:
  - jsoehner
