name: E2E Tests

on:
  workflow_run:
    workflows:
      - "Assets Build"
    types:
      - completed
    branches:
      - trunk

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run E2E Tests on Sauce Labs
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        BROWSER: remote
        TARGET: production
      run: |
        cd end-to-end-tests
        mvn clean test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: end-to-end-tests/target/surefire-reports 
