name: Room Service Build

on:
  push:
    paths:
      - 'room/**'
  pull_request:
    paths:
      - 'room/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build Room Service
      working-directory: ./room
      run: mvn clean install -Drevision=$(git rev-parse --short HEAD)
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/trunk'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and Push Docker image
      if: github.ref == 'refs/heads/trunk'
      working-directory: ./room
      run: |
        if [ -f target/restful-booker-platform-room-*-exec.jar ]; then
          VERSION=$(ls target/restful-booker-platform-room-*-exec.jar | cut -d '-' -f 5 | cut -c1-11)
          docker build -t mwinteringham/restfulbookerplatform_room:$VERSION .
          docker push mwinteringham/restfulbookerplatform_room:$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "Room JAR file not found"
          exit 1
        fi
    # Deploy to EC2
    - name: Deploy to EC2
      if: github.ref == 'refs/heads/trunk'
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
        chmod 600 ~/.ssh/private_key
        
        # Execute deployment commands directly via SSH
        DOCKER_IMAGE="mwinteringham/restfulbookerplatform_room:${VERSION}"
        echo "Deploying: ${DOCKER_IMAGE}"
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key ${EC2_USERNAME}@${EC2_HOST} "
          sudo docker pull ${DOCKER_IMAGE} && \
          sudo docker stop rbp-room || true && \
          sudo docker rm rbp-room || true && \
          sudo docker images -q mwinteringham/restfulbookerplatform_room | grep -v \$(sudo docker images ${DOCKER_IMAGE} -q) | xargs -r sudo docker rmi || true && \
          sudo docker run -d --network rbp-host --name rbp-room -p 3001:3001 -e dbRefresh='60' ${DOCKER_IMAGE}
        " 